"""initial

Revision ID: 2b129d5ffe17
Revises: 
Create Date: 2026-02-22 02:02:14.326928

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b129d5ffe17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('status',
                              sa.String(),
                              nullable=True,
                              comment='Статус задачи'),
                    sa.Column('object_key',
                              sa.String(),
                              nullable=True,
                              comment='Путь до файла в хранилище'),
                    sa.Column('file_name',
                              sa.String(),
                              nullable=True,
                              comment='Имя файла для обработки'),
                    sa.Column('updated_at',
                              sa.DateTime(timezone=True),
                              server_default=sa.text('now()'),
                              nullable=False,
                              comment='Дата изменения задачи'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Задача')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
